FROM python:3.12-slim

RUN pip install --no-cache-dir poetry==1.8.*

WORKDIR /app

COPY pyproject.toml poetry.lock* readme.md ./
COPY src/ ./src/
COPY alembic/ ./alembic/
COPY alembic.ini ./
COPY docker/seed/ ./docker/seed/

RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi

EXPOSE 8000

CMD ["uvicorn", "regulahub.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "/app/src"]
